### ISSUE TITLE
Downloads will not start

### ISSUE THREAD

**Issue by gotzlotz** [XITRIX/iTorrent_CSharp#2]
I’ve tried magnet and torrent. Will not start just says downloading but it isn’t downloading anything.

**Comment by XITRIX** [comment]
Can you please give me a link to this torrent file, I already have downloaded more than

**Comment by XITRIX** [comment]
Can you please give me a link to this torrent file, I've already downloaded more than 20GB by this app, and there was no any problems with it. I tested it on IPhone 8 Plus 11.3, IPad 2 9.3 and iPhone 5 10.x. But I know, that magnet is not working yet

![img_1654](https://user-images.githubusercontent.com/9553519/38610954-1911c9fe-3d8b-11e8-8c43-4b691880855f.PNG)
![img_1655](https://user-images.githubusercontent.com/9553519/38610968-2216227a-3d8b-11e8-9286-7a43c7dcfdb4.PNG)

**Comment by XITRIX** [comment]
I committed a new update, it should fix your problem
