### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by gotzlotz** [XITRIX/iTorrent_CSharp#4]
Is there a way to display the remaning time till it’s finished and connected peers?

**Comment by XITRIX** [comment]
No, but I'll add time remaining info in the nearest updates. 
But I don't understand about connected peers, what do you mean?

**Comment by gotzlotz** [comment]
Show how many seeds and peers you are connected too.

**Comment by XITRIX** [comment]
But it is available from the first versions of this app
![photo_2018-05-11_14-15-12](https://user-images.githubusercontent.com/9553519/39922155-700a1a42-5526-11e8-86af-4af0d05ad1d9.jpg)

**Comment by XITRIX** [comment]
Feature has been implemented in the latest release

**Comment by gotzlotz** [comment]
Sorry, I’m talking about in the torrent preview where you can see all the downloading torrents.

**Comment by XITRIX** [comment]
But I'm at a loss, why do you need this? It is not the main information that needs to be on the main screen, I think.
Also, there is not enough space to add this, so I'll need to add a new line for it, but on "finished" torrents there will be an empty line, or there will have a different size, which will looks ugly. I cannot find any good reason to add it

**Comment by gotzlotz** [comment]
I guess that is true...
